import type { Category } from './ingredient.ts';
import { normalizeName } from './text.ts';

/** A food name can be more specific than its shelf, including manually added "other" items. */
const FOODS: readonly [RegExp, string][] = [
  [/\b(?:ladyfingers?|palitos de champanhe|biscuits?|cookies?|bolachas?|galletas?)\b/, '🍪'],
  [/\b(?:seasoning|rub|adobo|misturas?|nutmeg|noz moscada|cinnamon|canela|cumin|cominhos?|curry|caril|xanthan|xantana)\b/, '🫙'],
  [/\b(?:bell peppers?|pimentos?|pimentoes|pimentao)\b/, '🫑'],
  [/\b(?:chili|chilli|paprika|pimenta|pimienta|pepper)\b/, '🌶️'],
  [/\b(?:tomato(?:es)?|tomates?)\b/, '🍅'],
  [/\b(?:peanut butter|manteiga de amendoim|crema de cacahuete)\b/, '🥜'],
  [/\b(?:ice cream|gelados?|sorvete|helados?)\b/, '🍨'],
  [/\b(?:coconut|coco)\b/, '🥥'],
  [/\b(?:strawberr(?:y|ies)|morangos?|fresas?)\b/, '🍓'],
  [/\b(?:blueberr(?:y|ies)|mirtilos?|arandanos?)\b/, '🫐'],
  [/\b(?:bananas?|platanos?)\b/, '🍌'],
  [/\b(?:pineapples?|ananas|abacaxi|pina)\b/, '🍍'],
  [/\b(?:mango(?:es|s)?|mangas?)\b/, '🥭'],
  [/\b(?:peaches|peach|pessegos?|melocotones?)\b/, '🍑'],
  [/\b(?:cherr(?:y|ies)|cerejas?|cerezas?)\b/, '🍒'],
  [/\b(?:watermelons?|melancias?|sandias?)\b/, '🍉'],
  [/\b(?:melons?|meloes|melao)\b/, '🍈'],
  [/\b(?:grapes?|uvas?)\b/, '🍇'],
  [/\b(?:lemons?|limoes|limao|limones?)\b/, '🍋'],
  [/\b(?:limes?|limas?)\b/, '🍋‍🟩'],
  [/\b(?:oranges?|laranjas?|naranjas?|tangerines?|clementines?)\b/, '🍊'],
  [/\b(?:apples?|macas?|manzanas?)\b/, '🍎'],
  [/\b(?:pears?|peras?)\b/, '🍐'],
  [/\b(?:kiwis?)\b/, '🥝'],
  [/\b(?:avocados?|abacates?|aguacates?)\b/, '🥑'],
  [/\b(?:carrots?|cenouras?|zanahorias?)\b/, '🥕'],
  [/\b(?:broccoli|brocolos|brocoli)\b/, '🥦'],
  [/\b(?:cucumbers?|pepinos?|courgettes?|zucchini|abobrinhas?|calabacin)\b/, '🥒'],
  [/\b(?:aubergines?|eggplants?|beringelas?|berenjenas?)\b/, '🍆'],
  [/\b(?:garlic|alho|ajo)\b/, '🧄'],
  [/\b(?:onions?|cebolas?|cebolla)\b/, '🧅'],
  [/\b(?:potato(?:es)?|batatas?|patatas?)\b/, '🥔'],
  [/\b(?:sweetcorn|corn|milho|maiz)\b/, '🌽'],
  [/\b(?:mushrooms?|cogumelos?|champinones?)\b/, '🍄'],
  [/\b(?:ginger|gengibre|jengibre)\b/, '🫚'],
  [/\b(?:lettuce|spinach|cabbage|kale|alface|espinafres|espinafre|couve|lechuga|espinacas?)\b/, '🥬'],
  [/\b(?:basil|mint|parsley|cilantro|coriander|oregano|oregano(?:s)?|rosemary|thyme|bay leaves|manjericao|hortela|salsa|coentros|oregaos|alecrim|louro|cebolinho|ervas)\b/, '🌿'],
  [/\b(?:eggs?|ovos?|huevos?)\b/, '🥚'],
  [/\b(?:butter|manteiga|mantequilla)\b/, '🧈'],
  [/\b(?:cheese|queijo|queso|mascarpone|parmesan|parmesao|mozzarella|ricotta|feta)\b/, '🧀'],
  [/\b(?:milk|leite|leche|cream|natas|yogurt|yoghurt|iogurte|yogur)\b/, '🥛'],
  [/\b(?:chicken|frango|pollo|turkey|peru|pavo)\b/, '🍗'],
  [/\b(?:beef|steak|pork|carne|bife|porco|cerdo)\b/, '🥩'],
  [/\b(?:bacon)\b/, '🥓'],
  [/\b(?:fish|salmon|tuna|peixe|salmao|atum|pescado|atun)\b/, '🐟'],
  [/\b(?:shrimp|prawns?|camarao|camaroes|gambas?)\b/, '🦐'],
  [/\b(?:rice|arroz)\b/, '🍚'],
  [/\b(?:pasta|spaghetti|noodles|massa|esparguete|macarrao|fideos)\b/, '🍝'],
  [/\b(?:bread|pao|pan|toast|tostas?)\b/, '🍞'],
  [/\b(?:croissants?)\b/, '🥐'],
  [/\b(?:flour|farinha|harina|oats|aveia|avena|barley|cevada|couscous|quinoa|wheat|trigo)\b/, '🌾'],
  [/\b(?:beans?|lentils?|chickpeas?|feijao|feijoes|lentilhas?|grao de bico|garbanzos?|lentejas?)\b/, '🫘'],
  [/\b(?:peanuts?|almonds?|hazelnuts?|walnuts?|cashews?|amendoim|amendoins|amendoas?|avelas?|nozes|caju|pistachios?|pistacios?)\b/, '🥜'],
  [/\b(?:olives?|azeite|azeitonas?|aceitunas?)\b/, '🫒'],
  [/\b(?:honey|mel|miel)\b/, '🍯'],
  [/\b(?:chocolate|cocoa|cacau|cacao|nutella)\b/, '🍫'],
  [/\b(?:sugar|acucar|azucar|erythritol|eritritol|stevia)\b/, '🍬'],
  [/\b(?:coffee|cafe)\b/, '☕'],
  [/\b(?:tea|cha|te|matcha)\b/, '🫖'],
  [/\b(?:juice|sumo|suco|zumo|jugo)\b/, '🧃'],
  [/\b(?:water|agua)\b/, '💧'],
  [/\b(?:wine|vinho|vino|moscatel)\b/, '🍷'],
  [/\b(?:beer|cerveja|cerveza)\b/, '🍺'],
  [/\b(?:vodka|rum|whisky|whiskey|gin|tequila)\b/, '🥃'],
  [/\b(?:salt|sal|glutamato|msg)\b/, '🧂'],
  [/\b(?:oil|oleo|aceite|vinegar|vinagre|vanilla|baunilha|vainilla|sauce|molho|salsa)\b/, '🫙'],
];

const CATEGORY_EMOJIS: Record<Category, string> = {
  dairy: '🥛', eggs: '🥚', 'meat-fish': '🥩', vegetables: '🥬', fruit: '🍎', grains: '🌾',
  legumes: '🫘', nuts: '🥜', 'herbs-spices': '🌿', flavouring: '🫙', condiments: '🫙',
  baking: '🧁', sweetener: '🍯', chocolate: '🍫', snacks: '🍿', drinks: '🥤', alcohol: '🍷', other: '🫙',
};

/** Specific food matches come first; the assigned shelf represents other ingredient names. */
export function ingredientEmoji(name: string, category: Category): string {
  const normalized = normalizeName(name);
  return FOODS.find(([pattern]) => pattern.test(normalized))?.[1] ?? CATEGORY_EMOJIS[category] ?? '🫙';
}
