import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const { JSDOM } = createRequire(process.env.PANTRY_UI_NODE_MODULES ? `${process.env.PANTRY_UI_NODE_MODULES}/package.json` : import.meta.url)('jsdom');
const base = fileURLToPath(new URL('../', import.meta.url)).replace(/\/$/, '');
const dom = new JSDOM(readFileSync(`${base}/public/index.html`, 'utf8'), { url: 'http://127.0.0.1:3210', pretendToBeVisual: true });
const { window } = dom;
let lastScroll;
window.scrollTo = (x, y) => { lastScroll = [x, y]; };
globalThis.requestAnimationFrame = window.requestAnimationFrame.bind(window);
globalThis.cancelAnimationFrame = window.cancelAnimationFrame.bind(window);
globalThis.setInterval = window.setInterval.bind(window);
globalThis.clearInterval = window.clearInterval.bind(window);
for (const key of ['window', 'document', 'location', 'history', 'localStorage', 'CustomEvent', 'HTMLElement', 'HTMLDialogElement', 'DOMParser', 'Node', 'navigator']) Object.defineProperty(globalThis, key, { value: key === 'window' ? window : window[key], configurable: true });
window.HTMLDialogElement.prototype.showModal = function () { this.open = true; };
window.HTMLDialogElement.prototype.close = function () { this.open = false; };
globalThis.confirm = () => true;
const { api } = await import(`${base}/public/js/api.js`);
const { sampleRecipe } = await import(`${base}/test/fakes/fixtures.ts`);
const { ingredientEmoji } = await import(`${base}/src/domain/ingredient-emoji.ts`);
const recipe = sampleRecipe();
let ingredients = [
 {id:1,name:'Tomatoes',category:'vegetables',notes:'Cherry variety',inStock:true,createdAt:'2026-10-04T12:00:00Z'},
 {id:2,name:'Basil',category:'vegetables',notes:'Fresh leaves',inStock:true,createdAt:'2026-10-03T12:00:00Z'},
 {id:3,name:'Milk',category:'dairy',notes:'Oat milk',inStock:false,createdAt:'2026-10-03T12:00:00Z'},
 {id:4,name:'Lemons',category:'fruit',notes:'',inStock:true,createdAt:'2026-10-02T12:00:00Z'},
].map(item=>({...item,emoji:ingredientEmoji(item.name,item.category)}));
let profile = {appliances:[{name:'Oven',details:'200°C max'},{name:'Blender',details:'1 L jug'}],dishTypes:[{name:'Dinner',details:'Main course'}],servings:2,units:'Metric',language:'English',preferences:'Vegetarian'};
let saved = [], suggestionPayload, completedUrl;
const clone = (data) => structuredClone(data);
Object.assign(api, {
 getAuthConfig:async()=>({mode:'local'}),
 getAccount:async()=>({user:{name:'Test cook',email:'cook@example.com',model:''},planUsageEnabled:true,showPlanWelcome:false}),
 listModels:async()=>({models:[]}),
 listIngredients:async()=>({ingredients:clone(ingredients),categories:['vegetables','dairy','fruit','other']}),
 listJobs:async()=>({jobs:[]}),
 addIngredient:async({name,category='other',notes=''})=>{const ingredient={id:ingredients.length+1,name,emoji:ingredientEmoji(name,category),category,notes,inStock:true,createdAt:new Date().toISOString()};ingredients.push(ingredient);return {status:'added',ingredient:clone(ingredient)};},
 updateIngredient:async(id,changes)=>{const ingredient=ingredients.find(i=>i.id===id);Object.assign(ingredient,changes);ingredient.emoji=ingredientEmoji(ingredient.name,ingredient.category);return {ingredient:clone(ingredient)};},
 deleteIngredient:async(id)=>{ingredients=ingredients.filter(i=>i.id!==id);},
 getProfile:async()=>({profile:clone(profile)}),
 updateProfile:async(data)=>{profile={...profile,...clone(data)};return {profile:clone(profile)};},
 resetProfile:async()=>({profile:clone(profile)}),
 listSavedRecipes:async()=>({recipes:clone(saved)}),
 suggestRecipes:async(data)=>{suggestionPayload=clone(data);return {job:{id:1,status:'succeeded',result:{recipes:[recipe]}}};},
 saveRecipe:async(recipe)=>{saved.push({id:1,recipe:clone(recipe)});return {ok:true};},
 deleteSavedRecipe:async(id)=>{saved=saved.filter(i=>i.id!==id);},
 completeSignIn:async(url)=>{completedUrl=url;return {ok:true};},
 signOut:async()=>({revoked:true}),
});
const tick=()=>new Promise(r=>setTimeout(r,20));
const $=s=>document.querySelector(s);
const button=(root,text)=>[...root.querySelectorAll('button')].find(b=>{const copy=b.cloneNode(true);copy.querySelectorAll('[aria-hidden="true"]').forEach(el=>el.remove());return copy.textContent.trim()===text;});
const input=(el,value)=>{el.value=value;el.dispatchEvent(new window.Event('input',{bubbles:true}));};
const submit=el=>el.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
const pick=(scope,value)=>[...scope.querySelectorAll('.wheel-item')].find(item=>item.textContent===value).click();
localStorage.setItem('pantry:stock.sort',JSON.stringify('za'));
await import(`${base}/public/js/main.js`);
await tick();
const stock=$('#view-stock');
assert.equal(document.body.dataset.page,'stock');
assert.equal(stock.hidden,false);
assert.equal(stock.querySelector('.pantry-stats').textContent,'3 in stock · 1 to restock');
assert.equal(stock.querySelectorAll('.item').length,4);
const produceNames=()=>[...stock.querySelector('.category .items').querySelectorAll('.item-copy strong')].map(el=>el.textContent);
const sortedNames=()=>[...stock.querySelectorAll('.stock-list .item-copy strong')].map(el=>el.textContent);
const chooseSort=(label)=>{stock.querySelector('.pantry-sort').click();button($('dialog.sort-sheet'),label).click();assert.equal($('dialog.sort-sheet'),null);};
assert.equal(stock.querySelectorAll('.category').length,2,'default groups by category despite a previously saved sort');
assert.deepEqual(produceNames(),['Tomatoes','Basil','Lemons'],'default preserves the ingredient order');
assert.equal(stock.querySelector('.pantry-sort').dataset.active,'false');
chooseSort('Date added: newest first');
assert.deepEqual(sortedNames(),['Tomatoes','Milk','Basil','Lemons'],'date sorting uses timestamps across categories with stable ties');
assert.equal(stock.querySelectorAll('.category').length,0,'sorting removes category headings');
chooseSort('Date added: oldest first');
assert.deepEqual(sortedNames(),['Lemons','Basil','Milk','Tomatoes']);
chooseSort('Name: A–Z');
assert.deepEqual(sortedNames(),['Basil','Lemons','Milk','Tomatoes']);
assert.equal(JSON.parse(localStorage.getItem('pantry:stock.sort')),'za','sort choices are not persisted');
stock.querySelector('.pantry-sort').click();
assert.equal(button($('dialog.sort-sheet'),'Name: A–Z').getAttribute('aria-pressed'),'true');
button($('dialog.sort-sheet'),'Name: Z–A').click();
assert.deepEqual(sortedNames(),['Tomatoes','Milk','Lemons','Basil']);
const categoryBeforeSort=stock.querySelector('[aria-label="Filter ingredients"]');
categoryBeforeSort.value='produce';categoryBeforeSort.dispatchEvent(new window.Event('change'));
stock.querySelector('.status-filter').click();
input(stock.querySelector('[type=search]'),'Fresh');
chooseSort('Date added: newest first');
assert.equal(categoryBeforeSort.value,'produce','sorting preserves category filter');
assert.equal(stock.querySelector('.status-filter').dataset.state,'in','sorting preserves stock filter');
assert.equal(stock.querySelectorAll('.item').length,1,'sorting preserves search');
input(stock.querySelector('[type=search]'),'');
categoryBeforeSort.value='';categoryBeforeSort.dispatchEvent(new window.Event('change'));
stock.querySelector('.status-filter').click();stock.querySelector('.status-filter').click();
chooseSort('Grouped by category');
assert.equal(stock.querySelectorAll('.category').length,2,'grouping can be restored manually');
chooseSort('Name: A–Z');
location.hash='#recipes';window.dispatchEvent(new window.HashChangeEvent('hashchange'));await tick();
location.hash='#stock';window.dispatchEvent(new window.HashChangeEvent('hashchange'));await tick();
assert.equal(stock.querySelectorAll('.category').length,2,'changing tabs resets sorting');
chooseSort('Name: A–Z');
const pager=document.querySelector('.pages');
Object.defineProperty(pager,'clientWidth',{value:400,configurable:true});
pager.scrollLeft=400;pager.dispatchEvent(new window.Event('scrollend'));await tick();
pager.scrollLeft=0;pager.dispatchEvent(new window.Event('scrollend'));await tick();
assert.equal(stock.querySelectorAll('.category').length,2,'changing slides resets sorting');
chooseSort('Name: A–Z');
window.dispatchEvent(new window.Event('pagehide'));
assert.equal(stock.querySelectorAll('.category').length,2,'leaving the page resets sorting');
chooseSort('Name: A–Z');
Object.defineProperty(document,'hidden',{value:true,configurable:true});
document.dispatchEvent(new window.Event('visibilitychange'));
Object.defineProperty(document,'hidden',{value:false,configurable:true});
assert.equal(stock.querySelectorAll('.category').length,2,'leaving the browser tab resets sorting');
console.log('PASS pantry sorting: grouped default, four global orders, filters and resets on tabs/slides/page exit');
assert.equal(stock.querySelectorAll('.status-filter').length,1);
const stockFilter=stock.querySelector('.status-filter');
assert.equal(stockFilter.dataset.state,'all');
stockFilter.click();
assert.equal(stock.querySelectorAll('.item').length,3);
stockFilter.click();
assert.equal(stock.querySelectorAll('.item').length,1);
assert.match(stock.querySelector('.item').textContent,/Milk/);
stockFilter.click();
assert.equal(stock.querySelectorAll('.item').length,4);
assert.equal(stock.querySelector('[data-ingredient-id="1"] .ingredient-emoji').textContent,'🍅');
assert.equal(stock.querySelector('[data-ingredient-id="1"] .ingredient-emoji').getAttribute('aria-hidden'),'true');
const unaffectedRow=stock.querySelector('[data-ingredient-id="2"]');
const unchangedShelf=unaffectedRow.closest('.category');
const unchangedItems=unchangedShelf.querySelector('.items');
const toggledRow=()=>stock.querySelector('[data-ingredient-id="1"]');
toggledRow().querySelector('.stock-toggle').click();await tick();
assert.equal(stock.querySelectorAll('.item').length,4,'All keeps unavailable ingredients visible');
assert.equal(toggledRow().classList.contains('out-of-stock'),true);
assert.match(toggledRow().querySelector('.stock-toggle').getAttribute('aria-label'),/^Out of stock:/);
assert.equal(toggledRow().querySelector('.stock-mark path').getAttribute('d'),'m6 6 12 12');
assert.equal(stock.querySelector('[data-ingredient-id="2"]'),unaffectedRow,'other ingredient rows stay mounted');
assert.equal(unaffectedRow.closest('.category'),unchangedShelf,'the shelf stays mounted');
assert.equal(unchangedShelf.querySelector('.items'),unchangedItems,'the animated items container stays mounted');
assert.equal(document.activeElement,toggledRow().querySelector('.stock-toggle'));
toggledRow().querySelector('.stock-toggle').click();await tick();
assert.equal(toggledRow().classList.contains('out-of-stock'),false);
assert.equal(toggledRow().classList.contains('fresh'),false,'restocking does not replay ingredient arrival animation');
assert.equal(stock.querySelector('[data-ingredient-id="2"]'),unaffectedRow);
const updateIngredient=api.updateIngredient;
api.updateIngredient=async()=>{throw new Error('Stock update failed');};
const beforeFailure=toggledRow();beforeFailure.querySelector('.stock-toggle').click();await tick();
assert.equal(toggledRow(),beforeFailure,'a failed stock change preserves the current row and status');
assert.equal(beforeFailure.querySelector('.stock-toggle').disabled,false);
api.updateIngredient=updateIngredient;
button(stock,'Add').click();
input($('dialog input'),'Cucumber'); submit($('dialog form')); await tick();
assert.equal(ingredients.length,5);
assert.equal(stockFilter.dataset.state,'all');
assert.equal(stock.querySelector('[data-ingredient-id="5"] .ingredient-emoji').textContent,'🥒');
const filter=stock.querySelector('[aria-label="Filter ingredients"]');
filter.value='produce';filter.dispatchEvent(new window.Event('change'));
assert.equal(stock.querySelectorAll('.item').length,3);
input(stock.querySelector('[type=search]'),'Fresh');
assert.equal(stock.querySelectorAll('.item').length,1);
assert.match(stock.querySelector('.item').textContent,/Basil/);
input(stock.querySelector('[type=search]'),'');filter.value='';filter.dispatchEvent(new window.Event('change'));
stockFilter.click();stockFilter.click();
stock.querySelector('.stock-toggle').click(); await tick();
assert.equal(ingredients.find(i=>i.name==='Milk').inStock,true);
assert.equal(stock.querySelectorAll('.item.leaving').length,1);
await new Promise(r=>setTimeout(r,500));
assert.equal(stock.querySelectorAll('.item').length,0);
stockFilter.click();
assert.equal(stock.querySelectorAll('.item').length,5);
stock.querySelector('[data-ingredient-id="2"] .item-edit').click();
input($('dialog input[aria-label=Name]'),'Fresh basil');submit($('dialog form'));await tick();
assert.equal(ingredients.find(i=>i.id===2).name,'Fresh basil');
console.log('PASS pantry: search, grouped filters, manual addition, restock and editing');
location.hash='#recipes';window.dispatchEvent(new window.HashChangeEvent('hashchange'));await tick();
const recipes=$('#view-recipes');
assert.equal(recipes.hidden,false);
assert.equal(recipes.querySelector('.form-options').open,false);
input(recipes.querySelector('[aria-label=Craving]'),'A cozy dinner');
pick(recipes.querySelector('[aria-label=Servings]'),'4');
const [oven,blender]=recipes.querySelectorAll('.appliance-choice');oven.click();blender.click();blender.click();assert.equal(oven.dataset.mode,'use');assert.equal(blender.dataset.mode,'avoid');const easy=recipes.querySelector('.difficulty-picker input[value=easy]');easy.checked=true;easy.dispatchEvent(new window.Event('change'));
submit(recipes.querySelector('form'));await tick();
assert.equal(suggestionPayload.craving,'A cozy dinner');assert.equal(suggestionPayload.servings,4);assert.deepEqual(suggestionPayload.appliances,['Oven']);assert.deepEqual(suggestionPayload.avoidAppliances,['Blender']);assert.equal(suggestionPayload.difficulty,'easy');
assert.equal(recipes.querySelectorAll('.suggestion-grid article').length,1);
recipes.querySelector('.recipe-bookmark').click();await tick();
assert.equal(saved.length,1);
assert.equal(recipes.querySelector('.recipe-bookmark').getAttribute('aria-pressed'),'true');
button(recipes,'Saved 1').click();
assert.equal(recipes.querySelectorAll('.saved-recipe').length,1);
recipes.querySelector('.recipe-open').click();
assert.match($('dialog').textContent,/Ingredients/);
{const sheet=$('dialog.recipe-detail');assert.deepEqual([...sheet.querySelectorAll('.recipe-tab')].map(t=>t.lastChild.textContent),['Overview','Ingredients','Method']);assert.equal(sheet.querySelector('.recipe-tab[aria-current]').lastChild.textContent,'Overview');assert.equal(sheet.querySelector('.recipe-prev').disabled,true);assert.match(sheet.querySelector('.recipe-next').textContent,/Ingredients/);
 const [overview,,method]=sheet.querySelectorAll('.recipe-page');assert.equal(overview.inert,false);assert.equal(method.inert,true);assert.match(overview.querySelector('.recipe-nutrition').textContent,/kcal/);assert.match(overview.querySelector('.nutrition-grid').textContent,/Protein/);
 if(recipe.tips.length){method.querySelector('.tips-button').click();const tips=$('dialog.recipe-tips');assert.equal(tips.querySelectorAll('li').length,recipe.tips.length);button(tips,'Got it').click();assert.equal($('dialog.recipe-tips'),null);}}
$('dialog button[aria-label="Close recipe"]').click();
console.log('PASS recipes: generation payload, bookmark, saved collection and detail sheet');
let recipeFinished=false;
api.suggestRecipes=async()=>({job:{id:2,status:'running'}});
api.getJob=async()=>({job:{id:2,status:recipeFinished?'succeeded':'running',result:{recipes:[recipe]}}});
submit(recipes.querySelector('form'));await tick();
assert.equal($('#recipe-progress').hidden,false);
assert.equal(recipes.querySelector('.recipe-results .spinner'),null);
const kitchen=$('#view-profile');
let profileReadCount=0, resolveProfile;
api.getProfile=()=>{profileReadCount++;return profileReadCount===1?Promise.reject(new Error('Connection interrupted')):new Promise(resolve=>{resolveProfile=resolve;});};
button($('.tabbar'),'Kitchen').click();await tick();
assert.equal(kitchen.querySelector('form').hidden,true,'an unloaded profile is never shown as an empty editable kitchen');
assert.match(kitchen.querySelector('[role=alert]').textContent,/Connection interrupted/);
assert.equal(kitchen.querySelector('.preference-status').hidden,true);
submit(kitchen.querySelector('form'));await tick();
assert.equal(profile.servings,2,'an unloaded form cannot overwrite saved preferences');
button(kitchen,'Try again').click();await tick();
assert.match(kitchen.querySelector('[role=status]').textContent,/Loading your kitchen/);
assert.equal(kitchen.querySelector('form').hidden,true);
window.dispatchEvent(new window.HashChangeEvent('hashchange'));await tick();
assert.equal(profileReadCount,2,'repeated activation shares the pending profile request');
resolveProfile({profile:clone(profile)});await tick();
api.getProfile=async()=>({profile:clone(profile)});
assert.equal(kitchen.querySelector('form').hidden,false);
assert.equal(kitchen.querySelector('.kitchen-load-state').hidden,true);
assert.equal(kitchen.querySelector('[aria-label=Servings]').getAttribute('aria-valuenow'),'2');
assert.equal(kitchen.querySelector('.preference-status').hidden,true,'autosave status stays hidden until an edit');
console.log('PASS kitchen loading: persistent failure, retry, no empty-form writes and pending-request deduplication');
assert.equal($('#recipe-progress').hidden,false,'progress survives tab navigation');
const {toast}=await import(`${base}/public/js/dom.js`);toast('Another action completed');
assert.equal($('#recipe-progress').hidden,false,'ordinary toasts do not replace job progress');
recipeFinished=true;await new Promise(r=>setTimeout(r,1600));
assert.equal($('#recipe-progress').hidden,true);
assert.equal(recipes.querySelector('.recipe-generator .primary').disabled,false);
console.log('PASS recipe progress: persistent across tabs and other toasts, clears on completion');
assert.equal(kitchen.querySelectorAll('.appliance').length,2);
pick(kitchen.querySelector('[aria-label=Servings]'),'3');
button(kitchen,'Add').click();
input($('dialog input'),'Air fryer');input($('dialog textarea'),'4 L basket');submit($('dialog form'));await tick();
assert.equal(profile.appliances.length,3);
assert.equal(profile.servings,2);
assert.equal(kitchen.querySelector('[aria-label=Servings]').getAttribute('aria-valuenow'),'3');
assert.equal(kitchen.querySelector('.preference-status').hidden,false,'an edit shows autosave status');
window.dispatchEvent(new window.Event('pagehide'));await tick();
assert.equal(profile.servings,3);
assert.match(kitchen.querySelector('.preference-status').textContent,/Changes saved/);
assert.equal(profile.appliances.length,3);
let resolveRefresh;
api.getProfile=()=>new Promise(resolve=>{resolveRefresh=resolve;});
window.dispatchEvent(new window.HashChangeEvent('hashchange'));await tick();
pick(kitchen.querySelector('[aria-label=Servings]'),'4');
resolveRefresh({profile:clone(profile)});await tick();
assert.equal(kitchen.querySelector('[aria-label=Servings]').getAttribute('aria-valuenow'),'4','late profile reads preserve edits made while they were pending');
api.getProfile=async()=>({profile:clone(profile)});
console.log('PASS kitchen: editable defaults, appliance addition preserves pending defaults, autosave');
button($('#account'),'Sign out').click();await tick();
assert.equal(document.body.dataset.page,'login');assert.equal($('.tabbar').hidden,true);
assert.ok(button($('#view-login'),'Continue with ChatGPT'));
console.log('PASS sign out and signed-out state');
console.log('UI interaction checks passed. Rendering requires a separate built-in Browser check.');
window.close();
