import { chromium } from '/home/gabi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
const directory=new URL('./direct-trial/',import.meta.url).pathname;
await mkdir(directory,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/home/gabi/.cache/ms-playwright/chromium-1223/chrome-linux64/chrome',args:['--force-device-scale-factor=3']});
const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true,colorScheme:'light',reducedMotion:'no-preference',recordVideo:{dir:directory,size:{width:1170,height:2532}}});
const page=await context.newPage();
await page.goto('http://127.0.0.1:3214/demo-session');
const welcome=page.getByRole('button',{name:'Got it',exact:true});if(await welcome.isVisible())await welcome.click();
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:directory+'phone.png'});
await page.waitForTimeout(750);
const mark=Date.now();
await page.getByRole('button',{name:'Switch to dark theme',exact:true}).click();
await page.waitForTimeout(2000);
await page.getByRole('button',{name:'Switch to light theme',exact:true}).click();
await page.waitForTimeout(1500);
const file=await page.video().path();
await context.close();await browser.close();
await writeFile(directory+'trial.json',JSON.stringify({file,mark,duration:Date.now()-mark},null,2));
console.log(JSON.stringify({file,mark,duration:Date.now()-mark}));
